/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharePayloadRouteImport } from './routes/share.$payload'
import { Route as ApiNarrateRouteImport } from './routes/api/narrate'
import { Route as ApiComposeRouteImport } from './routes/api/compose'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePayloadRoute = SharePayloadRouteImport.update({
  id: '/share/$payload',
  path: '/share/$payload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNarrateRoute = ApiNarrateRouteImport.update({
  id: '/api/narrate',
  path: '/api/narrate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposeRoute = ApiComposeRouteImport.update({
  id: '/api/compose',
  path: '/api/compose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/api/narrate': typeof ApiNarrateRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compose' | '/api/narrate' | '/share/$payload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/compose' | '/api/narrate' | '/share/$payload'
  id: '__root__' | '/' | '/api/compose' | '/api/narrate' | '/share/$payload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiComposeRoute: typeof ApiComposeRoute
  ApiNarrateRoute: typeof ApiNarrateRoute
  SharePayloadRoute: typeof SharePayloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$payload': {
      id: '/share/$payload'
      path: '/share/$payload'
      fullPath: '/share/$payload'
      preLoaderRoute: typeof SharePayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/narrate': {
      id: '/api/narrate'
      path: '/api/narrate'
      fullPath: '/api/narrate'
      preLoaderRoute: typeof ApiNarrateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compose': {
      id: '/api/compose'
      path: '/api/compose'
      fullPath: '/api/compose'
      preLoaderRoute: typeof ApiComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiComposeRoute: ApiComposeRoute,
  ApiNarrateRoute: ApiNarrateRoute,
  SharePayloadRoute: SharePayloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
