/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharePayloadRouteImport } from './routes/share.$payload'
import { Route as ApiComposeRouteImport } from './routes/api/compose'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePayloadRoute = SharePayloadRouteImport.update({
  id: '/share/$payload',
  path: '/share/$payload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComposeRoute = ApiComposeRouteImport.update({
  id: '/api/compose',
  path: '/api/compose',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/compose': typeof ApiComposeRoute
  '/share/$payload': typeof SharePayloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/compose' | '/share/$payload'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/compose' | '/share/$payload'
  id: '__root__' | '/' | '/api/compose' | '/share/$payload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiComposeRoute: typeof ApiComposeRoute
  SharePayloadRoute: typeof SharePayloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$payload': {
      id: '/share/$payload'
      path: '/share/$payload'
      fullPath: '/share/$payload'
      preLoaderRoute: typeof SharePayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compose': {
      id: '/api/compose'
      path: '/api/compose'
      fullPath: '/api/compose'
      preLoaderRoute: typeof ApiComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiComposeRoute: ApiComposeRoute,
  SharePayloadRoute: SharePayloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
